#pragma config(Motor,  port1,           driveFrontLeft, tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           driveFrontRight, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveBackLeft, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveBackRight, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armTopMiddle,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapultTop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           catapultBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           catapultMiddle, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          armBottom,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		// Drive
		int throttle = vexRT[Ch3];
		int turn = vexRT[Ch1];
		int strafe = vexRT[Ch4];
		motor[driveFrontLeft] = throttle + turn - strafe;
		motor[driveFrontRight] = throtte - turn + strafe;
		motor[driveBackRight] = throttle + turn + strafe;
		motor[driveBackLeft] = throttle - turn - strafe;
		// Catapult
		motor[catapultTop] = vexRT[Ch3Xmtr2];
		motor[catapultBottom] = vexRT[Ch3Xmtr2];
		motor[catapultMiddle] = vexRT[Ch3Xmtr2];
		// Arm
		motor[armTop] = vexRT[Ch2Xmtr2];
		motor[armMiddle] = vexRT[Ch2Xmtr2];
		motor[armBottom] = vexRT[Ch2Xmtr2];
	}


}
